# Generated by Django 5.0 on 2025-04-18 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_history_table'),
        ('user', '0005_alter_vehicle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='plate_number',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.AddField(
            model_name='history',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=False, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='user.vehicle'),
        ),
    ]
