# Generated by Django 5.0 on 2025-05-31 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_remove_history_plate_number_remove_history_user_and_more'),
        ('user', '0007_user_role_alter_user_email_alter_vehicle_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='parking_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.parkingspace'),
        ),
    ]
