# Generated by Django 5.0 on 2025-04-17 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_phone_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicles',
        ),
    ]
