# Generated by Django 5.0 on 2025-04-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_vehicle_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
