# Generated by Django 5.0 on 2025-05-31 15:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_balance_transactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('customer', 'Normal User')], default='customer', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('space_number', models.CharField(max_length=10)),
                ('level', models.IntegerField()),
                ('is_occupied', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parkingspace',
                'unique_together': {('level', 'space_number')},
            },
        ),
    ]
